#!/usr/bin/env python

verbose     = False
daemonize   = True
sleep       = 10

# directory that should be watched for changes
watch_paths = [
    "/usr/local/ackstorm/sync",
    "/etc/fstab",
    "/etc/hosts",
    "/etc/resolv.conf",
    "/run/resolvconf/resolv.conf"
]

# Do not sync this files (RSYNC FILTER FORMAT)
excludes    = [
    '*/.#*',
    '*~',
    '*/.git/',
    '*.pyo',
    '*.pyc',
    
    '/var/tmp/**',
    '/var/log/**'
]

# Excludes for inotify (use only if too much noise is generated by inotify)
# This format is "regex" and can be only directories:
# https://github.com/seb-m/pyinotify/issues/31

inotify_excludes = [
    '^/var/log',
    '^/tmp'
]
